# Generated by Django 5.1.7 on 2025-06-30 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_employeeprofile_photo'),
        ('profiles', '0002_skill_employeeprofile_skills'),
    ]

    operations = [
    ]
