# Generated by Django 5.1.7 on 2025-06-30 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_skill_employeeprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dte',
            field=models.CharField(default='未設定', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='enterprise_id',
            field=models.CharField(default='unknown', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='mail_address',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='ml',
            field=models.DateField(default=datetime.date(2025, 6, 30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='statement_id',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
