# Generated by Django 5.1.7 on 2025-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_employeeprofile_department_employeeprofile_dte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='ml',
            field=models.IntegerField(),
        ),
    ]
