# Generated by Django 5.1.7 on 2025-06-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_employeeprofile_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='ml',
            field=models.CharField(choices=[('1', 'SMD'), ('2-4', 'Managing Director'), ('5', 'Associate Director'), ('6', 'Senior Manager'), ('7', 'Manager'), ('8', 'Associate Manager'), ('9', 'Team Lead/Consultant'), ('10', 'Sonior Analyst'), ('11', 'Analyst'), ('12', 'Associate'), ('13', 'New Associate')], default='11', max_length=50),
        ),
    ]
