# Generated by Django 5.1.7 on 2025-06-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_preemploymenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preemploymenthistory',
            name='employee',
        ),
        migrations.AddField(
            model_name='preemploymenthistory',
            name='employee_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pre_employment_histories', to='profiles.employeeprofile'),
        ),
    ]
