# Generated by Django 5.1.7 on 2025-06-30 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_preemploymenthistory_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preemploymenthistory',
            name='employee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_employment_histories', to='profiles.employeeprofile'),
        ),
    ]
