# Generated by Django 5.1.7 on 2025-06-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_employeeprofile_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='ml',
            field=models.CharField(choices=[('1', '1：SMD'), ('2-4', '2：Managing Director'), ('5', '3：Associate Director'), ('6', '4：Senior Manager'), ('7', '5：Manager'), ('8', '6：Associate Manager'), ('9', '7：Team Lead/Consultant'), ('10', '8：Senior Analyst'), ('11', '9：Analyst'), ('12', '10：Associate'), ('13', '11：New Associate')], default='11', max_length=50),
        ),
    ]
