# Generated by Django 5.1.7 on 2025-06-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_employeeprofile_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
