# Generated by Django 5.1.7 on 2025-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_employee_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
    ]
