# Generated by Django 5.2.3 on 2025-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
