# Generated by Django 5.1.7 on 2025-07-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ml',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='11', max_length=50, null=True),
        ),
    ]
